[package]
name = "funds-program"
version = "0.0.1"
description = "Quartz funds program"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "funds_program"

[features]
default = []
cpi = ["no-entrypoint"]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
idl-build = ["anchor-lang/idl-build", "anchor-spl/idl-build"]
local = []
devnet = []

[dependencies]
anchor-lang = "0.29.0"
anchor-spl = "0.29.0"
drift = { git = "https://github.com/drift-labs/protocol-v2", rev="babed162b08b1fe34e49a81c5aa3e4ec0a88ecdf", features = ["cpi"] }
