[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
funds_program = "dRiftyHA39MWEi3m9aunc5MzRF1JYuBsbn6VPcn33UH"

[programs.devnet]
funds_program = "dRiftyHA39MWEi3m9aunc5MzRF1JYuBsbn6VPcn33UH"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"


[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/$TEST_FILE"

[test]
startup_wait = 5000